-- MySQL Script generated by MySQL Workbench
-- 02/05/16 10:50:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HelpDesk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HelpDesk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HelpDesk` DEFAULT CHARACTER SET utf8 ;
USE `HelpDesk` ;

-- -----------------------------------------------------
-- Table `HelpDesk`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `nameRole` VARCHAR(45) NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `patronomic` VARCHAR(45) NULL,
  `password` VARCHAR(20) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `numberPhone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Role_idRole` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_User_Role_idx` (`Role_idRole` ASC),
  CONSTRAINT `fk_User_Role`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `HelpDesk`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`Tickets` (
  `idTickets` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NOT NULL,
  `discribe` VARCHAR(1000) NULL,
  `status` VARCHAR(45) NULL,
  `priority` VARCHAR(45) NULL,
  `comeDate` DATETIME NULL,
  `starDate` DATETIME NULL,
  `endDate` DATETIME NULL,
  PRIMARY KEY (`idTickets`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`File` (
  `idFile` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `format` VARCHAR(10) NULL,
  `file_hash` VARCHAR(512) NULL,
  `file_size` VARCHAR(11) NULL,
  PRIMARY KEY (`idFile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`Answer` (
  `idAnswer` INT NOT NULL,
  `data` DATETIME NULL,
  `text` VARCHAR(200) NULL,
  `Tickets_idTickets` INT NOT NULL,
  PRIMARY KEY (`idAnswer`),
  INDEX `fk_Answer_Tickets1_idx` (`Tickets_idTickets` ASC),
  CONSTRAINT `fk_Answer_Tickets1`
    FOREIGN KEY (`Tickets_idTickets`)
    REFERENCES `HelpDesk`.`Tickets` (`idTickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`Deprtment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`Deprtment` (
  `idDeprtment` INT NOT NULL AUTO_INCREMENT,
  `departName` VARCHAR(45) NULL,
  PRIMARY KEY (`idDeprtment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`Organization` (
  `idOrganization` INT NOT NULL AUTO_INCREMENT,
  `organName` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `orgNomber` VARCHAR(45) NULL,
  PRIMARY KEY (`idOrganization`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`Employer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`Employer` (
  `idEmployer` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Deprtment_idDeprtment` INT NOT NULL,
  PRIMARY KEY (`idEmployer`),
  INDEX `fk_Employer_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Employer_Deprtment1_idx` (`Deprtment_idDeprtment` ASC),
  CONSTRAINT `fk_Employer_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `HelpDesk`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employer_Deprtment1`
    FOREIGN KEY (`Deprtment_idDeprtment`)
    REFERENCES `HelpDesk`.`Deprtment` (`idDeprtment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT NOT NULL,
  `Organization_idOrganization` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `fk_Client_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Client_Organization1_idx` (`Organization_idOrganization` ASC),
  CONSTRAINT `fk_Client_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `HelpDesk`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_Organization1`
    FOREIGN KEY (`Organization_idOrganization`)
    REFERENCES `HelpDesk`.`Organization` (`idOrganization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`User_has_Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`User_has_Tickets` (
  `idUser_has_Tickets` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT NULL,
  `Tickets_idTickets` INT NULL,
  PRIMARY KEY (`idUser_has_Tickets`),
  INDEX `fk_User_has_Tickets_Tickets1_idx` (`Tickets_idTickets` ASC),
  INDEX `fk_User_has_Tickets_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_User_has_Tickets_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `HelpDesk`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Tickets_Tickets1`
    FOREIGN KEY (`Tickets_idTickets`)
    REFERENCES `HelpDesk`.`Tickets` (`idTickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`Tickets_has_File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`Tickets_has_File` (
  `id_Tickets_has_File` INT NOT NULL AUTO_INCREMENT,
  `Tickets_idTickets` INT NOT NULL,
  `File_idFile` INT NOT NULL,
  INDEX `fk_Tickets_has_File_Tickets1_idx` (`Tickets_idTickets` ASC),
  PRIMARY KEY (`id_Tickets_has_File`),
  INDEX `fk_Tickets_has_File_File1_idx` (`File_idFile` ASC),
  CONSTRAINT `fk_Tickets_has_File_Tickets1`
    FOREIGN KEY (`Tickets_idTickets`)
    REFERENCES `HelpDesk`.`Tickets` (`idTickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_has_File_File1`
    FOREIGN KEY (`File_idFile`)
    REFERENCES `HelpDesk`.`File` (`idFile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpDesk`.`Answer_has_File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpDesk`.`Answer_has_File` (
  `idAnswer_has_File` INT NOT NULL,
  `File_idFile` INT NOT NULL,
  `Answer_idAnswer` INT NOT NULL,
  PRIMARY KEY (`idAnswer_has_File`),
  INDEX `fk_Answer_has_File_File1_idx` (`File_idFile` ASC),
  INDEX `fk_Answer_has_File_Answer1_idx` (`Answer_idAnswer` ASC),
  CONSTRAINT `fk_Answer_has_File_File1`
    FOREIGN KEY (`File_idFile`)
    REFERENCES `HelpDesk`.`File` (`idFile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Answer_has_File_Answer1`
    FOREIGN KEY (`Answer_idAnswer`)
    REFERENCES `HelpDesk`.`Answer` (`idAnswer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
